### ISSUE TITLE
Add the Addy-React-Native documentation into Wiki

### ISSUE THREAD

**Issue by yashovardhan** [addy-org/Addy-React-Native#7]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**

There must be a documentation for Addy-React-Native on the Addy Wiki page

**Steps to reproduce:**
1. Copy the contents of the README.md file from Addy-React-Native
2. Using the Sample posts make a new post in the Addy Wiki Page and paste the contents
3. Follow the format of the Sample Post

**Comment by ananya** [comment]
i will like to do this

**Comment by yashovardhan** [comment]
first join the gitter chat and github organisation(link is there on the gitter chat description), ask on the gitter channel and you can be assigned the issue 😄

**Comment by yashovardhan** [comment]
@ananya-agrawal if you're having some trouble you can ask here right away

**Comment by ananya** [comment]
i added it but maybe its not getting commited

**Comment by yashovardhan** [comment]
first I told you how to get an issue assigned, secondly, you don't have to add it to the wiki of the repository,
there's a different repository called Addy Wiki where this should be committed
